'use strict'

module.exports = [
  {
    firstName: 'Hugo',
    lastName: 'Rambaut',
    email: 'hrambaut0@smugmug.com',
    homeAddress: '8485 Elka Park',
    username: 'hrambaut0',
    password: 'oSCqdeP',
  },
  {
    firstName: 'Shayne',
    lastName: 'Swansborough',
    email: 'sswansborough1@mozilla.org',
    homeAddress: '1282 Stoughton Trail',
    username: 'sswansborough1',
    password: '9Fv9YSoF',
  },
  {
    firstName: 'Rhetta',
    lastName: 'Kegan',
    email: 'rkegan2@blogtalkradio.com',
    homeAddress: '1343 West Drive',
    username: 'rkegan2',
    password: 'EMcClraj',
  },
  {
    firstName: 'Ralf',
    lastName: 'Mullinger',
    email: 'rmullinger3@tamu.edu',
    homeAddress: '3 Ilene Pass',
    username: 'rmullinger3',
    password: '4eVsxG1Qa',
  },
  {
    firstName: 'Brook',
    lastName: 'Meineking',
    email: 'bmeineking4@nhs.uk',
    homeAddress: '632 Sugar Lane',
    username: 'bmeineking4',
    password: 'u0I2biEn',
  },
  {
    firstName: 'Hillary',
    lastName: 'Capponeer',
    email: 'hcapponeer5@gizmodo.com',
    homeAddress: '914 Del Mar Hill',
    username: 'hcapponeer5',
    password: 'UIzEHU',
  },
  {
    firstName: 'Kissie',
    lastName: 'Langfat',
    email: 'klangfat6@acquirethisname.com',
    homeAddress: '68344 Kropf Lane',
    username: 'klangfat6',
    password: 'ia6BVB',
  },
  {
    firstName: 'Philomena',
    lastName: 'Demkowicz',
    email: 'pdemkowicz7@examiner.com',
    homeAddress: '195 Lighthouse Bay Terrace',
    username: 'pdemkowicz7',
    password: 'd3nhZZkrKDH',
  },
  {
    firstName: 'Venita',
    lastName: 'Lebbon',
    email: 'vlebbon8@cocolog-nifty.com',
    homeAddress: '9 Sunfield Trail',
    username: 'vlebbon8',
    password: 'tkF3sOoX',
  },
  {
    firstName: 'Randy',
    lastName: 'De Biasio',
    email: 'rdebiasio9@va.gov',
    homeAddress: '9182 Old Gate Pass',
    username: 'rdebiasio9',
    password: 'GVClpaU',
  },
  {
    firstName: 'Bealle',
    lastName: 'Megainey',
    email: 'bmegaineya@auda.org.au',
    homeAddress: '2 Arrowood Plaza',
    username: 'bmegaineya',
    password: 'M1RNijWHXTHR',
  },
  {
    firstName: 'Elise',
    lastName: 'Pingstone',
    email: 'epingstoneb@cbslocal.com',
    homeAddress: '139 Mosinee Hill',
    username: 'epingstoneb',
    password: 'Eq2HLCUSv',
  },
  {
    firstName: 'Rudiger',
    lastName: 'Diament',
    email: 'rdiamentc@dedecms.com',
    homeAddress: '973 Rigney Court',
    username: 'rdiamentc',
    password: 'CTAidBSDy',
  },
  {
    firstName: 'Mendie',
    lastName: 'Cartmell',
    email: 'mcartmelld@zimbio.com',
    homeAddress: '37 Springview Plaza',
    username: 'mcartmelld',
    password: 'WBgedM9K4',
  },
  {
    firstName: 'Derron',
    lastName: 'Londer',
    email: 'dlondere@cam.ac.uk',
    homeAddress: '82 Graedel Terrace',
    username: 'dlondere',
    password: 'I5LvM3jMldKW',
  },
]
